name: Publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
      - name: Get mod name
        uses: SebRollen/toml-action@v1.0.0
        id: get_mod_name
        with:
          file: src/main/resources/META-INF/mods.toml
          field: mods.0.displayName
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get_mod_name.outputs.value }}-${{ github.event.release.tag_name || 'test' }}.jar
          path: build/libs/
      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          curseforge-id: 394468
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: build/libs/*.jar
